expensify:
  url: https://integrations.expensify.com/Integration-Server/ExpensifyIntegrations
  partnerUserId: aa_harishsanjay48_gmail_com
  partnerUserSecret: 
  templateFilePath: D:\\Project\\expensify-accounting-systems\\src\\main\\resources\\expensify_template.ftl
spring:
  application:
    name: expensify-accounting-systems
    
  data:
    mongodb:
      uri: 
      database: accounting-systems

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
